
project_id = "nqbcxrujjxwgoyjxmmla"
# This is a placeholder config file for edge functions.
# The real configurations are applied and stored in the Supabase database.

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.verify-payment]
verify_jwt = true

[functions.send-trial-reminder]
verify_jwt = true

[functions.webhook-stripe]
verify_jwt = false

[functions.calculate-proration]
verify_jwt = true

[functions.create-midtrans-payment]
verify_jwt = true

[functions.webhook-midtrans]
verify_jwt = false
