
project_id = "nqbcxrujjxwgoyjxmmla"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
file_size_limit = "50MiB"

[auth]
site_url = "https://app.profitloop.id"
additional_redirect_urls = ["https://localhost:3000", "https://profitloop.id", "https://app.profitloop.id", "https://preview--profitloop-ver1.lovable.app"]
jwt_expiry = 3600
enable_signup = true

[functions]
[functions.create-profile-if-not-exists]
verify_jwt = false

[functions.cors]
enabled = true
allowed_origins = ["https://profitloop.id", "https://app.profitloop.id", "https://preview--profitloop-ver1.lovable.app", "http://localhost:3000"]
allowed_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
allowed_headers = ["X-Requested-With", "Content-Type", "Accept", "Authorization", "x-client-info", "apikey"]
