
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqbcxrujjxwgoyjxmmla.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xYmN4cnVqanh3Z295anhtbWxhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMjA3ODAsImV4cCI6MjA2MTU5Njc4MH0.ksytXhQEPyaHVNCmmFd45FgC58Nyn3MOkSdioIqUiwQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true,
      flowType: 'implicit' // Add this to prevent email confirmation issues
    }
  }
);

// Helper function to update user metadata with organization info
export async function updateUserOrgMetadata(organizationId: string, role: string) {
  try {
    // Update user metadata with organization_id and role
    const { error } = await supabase.auth.updateUser({
      data: { 
        organization_id: organizationId,
        role: role
      }
    });
    
    if (error) {
      console.error("Error updating user metadata:", error);
      return false;
    }
    
    return true;
  } catch (err) {
    console.error("Exception updating user metadata:", err);
    return false;
  }
}

// Helper function to force email verification bypass
export async function forceSignIn(email: string, password: string) {
  try {
    // First try normal sign in
    const { data, error } = await supabase.auth.signInWithPassword({
      email,
      password
    });
    
    if (!error) {
      return { data, error: null };
    }
    
    // If error is email confirmation, attempt a special sign-in
    if (error.message.includes("not confirmed") || error.message.includes("Email not confirmed")) {
      console.log("Attempting to bypass email verification...");
      
      // Clear any stored session/auth data that might be causing issues
      await supabase.auth.signOut();
      
      // Retry sign in after a short delay
      await new Promise(resolve => setTimeout(resolve, 500));
      
      return await supabase.auth.signInWithPassword({
        email,
        password
      });
    }
    
    return { data, error };
  } catch (err) {
    console.error("Force sign in error:", err);
    return { data: null, error: err as Error };
  }
}
